# Generated by Django 4.0 on 2021-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211207_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=50)),
                ('player_one', models.CharField(max_length=255)),
                ('player_two', models.CharField(blank=True, max_length=255, null=True)),
                ('game_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
