# Generated by Django 4.0 on 2021-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_winsmodel_delete_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winsmodel',
            options={'ordering': ['-wins']},
        ),
        migrations.AlterField(
            model_name='winsmodel',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
