# Generated by Django 4.0 on 2021-12-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_winsmodel_options_alter_winsmodel_wins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winsmodel',
            options={'ordering': ['wins']},
        ),
    ]
