# Generated by Django 4.0 on 2021-12-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_winsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winsmodel',
            options={'ordering': ['-wins']},
        ),
    ]
