#adapted from example in docker documentation
version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    user: 1001:1002 #(for linux)
    command: python /code/assignment3/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
       - web
    ports:
       - 80:80
    links:
       - web:web
       
  redis:
    image: redis:latest
    expose:
       - 6379